name: course
channels:
  - conda-forge
dependencies:
  - cmasher
  - jupyter
  - lxml
  - pandas
  - pillow
  - pyarrow
  - requests
  - scipy
  - seaborn
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - matplotlib
  - numpy
  - scikit-learn
  - linkify-it-py
  - pip
  - xgboost=1.6.2
  - tensorflow
  - umap-learn
  - pip:
      - adjustText
      - highlight-text
      - kloppy
      - mplsoccer
      - sphinxcontrib-youtube
      - sphinx-gallery
      - sphinxcontrib.bibtex
      - myst-parser
      - ruptures
